spring:
  application:
    name: gateway-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka-server-url}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}